project:
  type: website
  output-dir: docs

website:
  title: "Basma Khaled — MBA Portfolio"
  site-url: "https://bg-a.github.io/Basma-Greatly-BG-Website/"
  search: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Skills"
        href: skills.qmd
      - text: "Leadership"
        href: leadership.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "Reflection"
        href: reflection.qmd
      - text: "Appendix"
        href: appendix/index.qmd
    right:
      - text: "Download CV (PDF)"
        href: basma-elgreatly-resume/Basma_Khaled_Resume.pdf   # or Appendix.pdf until your CV is ready
      - icon: linkedin
        href: https://www.linkedin.com/in/YOUR-LINKEDIN-HANDLE
      - icon: github
        href: https://github.com/bg-a
  page-footer:
    center: "© 2025 Basma Khaled · MBA Portfolio"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true


