project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - resume.qmd
    - projects.qmd
    - skills.qmd
    - leadership.qmd
    - contact.qmd
    - reflection.qmd
    - appendix/index.qmd

website:
  title: "Basma Khaled — MBA Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Skills & Certifications"
        href: skills.qmd
      - text: "Leadership"
        href: leadership.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "Reflection"
        href: reflection.qmd
      - text: "Appendix"
        href: appendix/index.qmd
    right:
      - text: "Download CV (PDF)"
        href: Appendix.pdf
   # change or create this file as noted below

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    smooth-scroll: true

