project:
  type: website
  output-dir: docs   # if you're publishing from /docs on GitHub Pages
website:
  title: "Basma Khaled — MBA Portfolio"
  favicon: img/favicon.png
  navbar:
    logo: img/logo.png
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd
      - text: Skills
        href: skills.qmd
      - text: Leadership
        href: leadership.qmd
      - text: Contact
        href: contact.qmd
      - text: Reflection
        href: reflection.qmd
      - text: Appendix
        href: appendix.qmd
    right:
      - text: "Download CV (PDF)"
        href: files/Basma-Elgreatly-CV.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/basma-elgreatly/
      - icon: github
        href: https://github.com/bg-a
format:
  html:
    theme: 
      - cosmo
      - theme/brand-blue.scss
    toc: true
    page-layout: full
    smooth-scroll: true
    link-external-newwindow: true
    code-link: false
    callout-appearance: simple
execute:
  freeze: auto



